name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Copy project to EC2 (SCP)
        run: |
          ssh -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST "mkdir -p /home/$EC2_USER/groupe9"
          scp -i ~/.ssh/id_rsa -r ./ $EC2_USER@$EC2_HOST:/home/$EC2_USER/groupe9
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Install dependencies and run app
        run: |
          ssh $EC2_USER@$EC2_HOST << 'EOF'

          APP_DIR=/home/$EC2_USER/groupe9
          LOG_DIR=$APP_DIR/logs

          cd $APP_DIR

          # créer dossier logs persistant
          mkdir -p $LOG_DIR

          # créer venv seulement s'il n'existe pas
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          # installer dépendances
          venv/bin/pip install -r requirements.txt

          # arrêter ancienne app
          pkill -f run.py || true

          # lancer application avec vrai log serveur
          nohup venv/bin/python run.py >> $LOG_DIR/app.log 2>&1 &

          echo "Application démarrée, logs disponibles ici:"
          echo "$LOG_DIR/app.log"

          EOF
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
